### ISSUE TITLE
Using FOSUserBundle as Provider

### ISSUE THREAD

**Issue by ghost** [djoos/EscapeWSSEAuthenticationBundle#31]
Hi,

I have completed programming an API and I'm looking into securing it using WSSE.
I'm having some trouble getting authenticated to the secured parts of the api.

My configuration is as follows:

security.yml

```
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
       wsse_secured:
          pattern:   ^/api/.*
          wsse:
            lifetime: 300 #lifetime of nonce
            realm: "Secured API" #identifies the set of resources to which the authentication information will apply (WWW-Authenticate)
            profile: "UsernameToken" #WSSE profile (WWW-Authenticate)
            encoder: #digest algorithm
                algorithm: sha512
          anonymous: true
          provider: fos_userbundle

    access_control:
            - { path: ^/api.*, role: ROLE_USER }
            - { path: ^/security.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

```

config.yml

```
...
fos_user:
    db_driver: orm
    firewall_name: wsse_secured
    user_class: MyCompany\UserBundle\Entity\User


escape_wsse_authentication:
    authentication_provider_class: Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider
    authentication_listener_class: Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener
    authentication_entry_point_class: Escape\WSSEAuthenticationBundle\Security\Http\EntryPoint\EntryPoint
    authentication_encoder_class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
...
```

SecurityController.php

```
/**
     * WSSE Token generation
     *
     * @Rest\View
     *
     * @return FOSView
     * @throws AccessDeniedException
     */
    public function postTokenCreateAction()
    {

        $view = FOSView::create();
        $request = $this->getRequest();

        $username = $request->get('_username');
        $password = $request->get('_password');

        //$csrfToken = $this->container->get('form.csrf_provider')->generateCsrfToken('authenticate');
        //$data = array('csrf_token' => $csrfToken,);

        $um = $this->get('fos_user.user_manager');
        $user = $um->findUserByUsernameOrEmail($username);

        if (!$user instanceof User) {
            throw new AccessDeniedException("Wrong user");
        }

        $created = date('c');
        $nonce = substr(md5(uniqid('nonce_', true)), 0, 16);
        $nonceHigh = base64_encode($nonce);
        $passwordDigest = base64_encode(sha1($nonce . $created . $password . "{".$user->getSalt()."}", true));
        $header = "UsernameToken Username=\"{$username}\", PasswordDigest=\"{$passwordDigest}\", Nonce=\"{$nonceHigh}\", Created=\"{$created}\"";
        $view->setHeader("Authorization", 'WSSE profile="UsernameToken"');
        $view->setHeader("X-WSSE", "UsernameToken Username=\"{$username}\", PasswordDigest=\"{$passwordDigest}\", Nonce=\"{$nonceHigh}\", Created=\"{$created}\"");
        $data = array('WSSE' => $header);
        $view->setStatusCode(200)->setData($data);
        return $view;
    }
```

The tokens are getting generated by doing
POST /security/create_token.json?username=myusername&password="plaintextpassword" over SSL
But when I use that token with a X-WSSE header to go to
GET /api/me
I keep getting a 401 Not Authorized.

Any ideas? Did I misinterpreted the documentation?
