### ISSUE TITLE
WSSE authentication failed

### ISSUE THREAD

**Issue by Danny-P** [djoos/EscapeWSSEAuthenticationBundle#46]
Hi,

I try to integrate FOSUserBundle with EscapeWSSEAuthenticationBundle. 
I read and worked through the other issues related to this. But I still have an error "WSSE authentication failed" in my logs and it don't work. 

Here is my security.yml:
 security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

```
role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

providers:
    fos_userbundle:
        id: fos_user.user_provider.username_email

firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

    wsse_secured:
        pattern: ^/api/.*
        wsse:
            realm: "Gesicherte API. Bitte anmelden!"
            profile: "UsernameToken"
            lifetime: 300
            encoder:
                algorithm: sha512
        anonymous: false
        provider: fos_userbundle

    main:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
        logout: true
        anonymous: true

access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
```

That's the relevant part of config.yml
fos_rest:
    view:
        view_response_listener: true

fos_user:
    db_driver: orm
    firewall_name: wsse_secured
    user_class: dpn\DienstplanBundle\Entity\User

escape_wsse_authentication:
    authentication_provider_class: Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider
    authentication_listener_class: Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener
    authentication_entry_point_class: Escape\WSSEAuthenticationBundle\Security\Http\EntryPoint\EntryPoint
    authentication_encoder_class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder

In vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php I debugged into validateDiget Method. The value in $expected is not the same as in $digest. 

For testing I used http://www.teria.com/~koseki/tools/wssegen/ for generating WSSE Header. I put in my username and the hashed password, taken from the database. Nonce and Created are set to auto. I took the generated WSSE Header and tried to test my api with the Chrome Rest Console. 

There I get an error 401.

Are there any known errors or have I missed something?

I use symfony version 2.4.4, FOSUser version 2.0.0 and EscapeWSSEAuthenticationBundle 2.3.1
