### ISSUE TITLE
Integration with FOSUserBundle : 401 status code

### ISSUE THREAD

**Issue by benjamin-hubert** [djoos/EscapeWSSEAuthenticationBundle#53]
Hi,

I'm having the same problem as @djoos was having and i followed every step of your discussion on #49  without success.

The only difference from your tutorial is that i'm using sha512 as FOS encoder. So i changed the encoder parameter to sha512 and made a custom function to generate my token (based on https://github.com/sdiaz/FOSRestBundleByExample/blob/master/src/ByExample/DemoBundle/Controller/SecurityController.php#L64 ).

Still without success, please could you explain what i've been doing wrong ?

Thank's

PS : here is my code 

``` yaml
security:
    providers:
        main:
           id: fos_user.user_provider.username
      wsse_secured:
          pattern: ^/api/.*
          anonymous: false
          provider: main
          wsse:
              lifetime: 31556926
              realm: "Secured API"
              profile: "UsernameToken"
              encoder:
                 algorithm: sha512
                 encodeHashAsBase64: true
                 iterations: 1
    encoders:
       Alpixel\Component\UserBundle\Entity\User: sha512
```

I also made the modification about the Authentication provider
