### ISSUE TITLE
Problem with multi Authentication providers

### ISSUE THREAD

**Issue by MGDSoft** [djoos/EscapeWSSEAuthenticationBundle#69]
Hi djoos!

I have a problem with following configuration

```yml
    api:
            pattern:   ^/api/v.*
            stateless: true
            provider: api_user
            wsse:
                realm: "%api_wsse_realm%" #identifies the set of resources to which the authentication information will apply (WWW-Authenticate)
                profile: "%api_wsse_profile%" #WSSE profile (WWW-Authenticate)
                lifetime: "%api_wsse_lifetime%"

                encoder:
                    algorithm: "%api_wsse_algorithm%"
                    encodeHashAsBase64: "%api_wsse_encodehashasbase64%"
                    iterations: "%api_wsse_iterations%"
            http_basic:  ~

```

Http_basic make it crash with "This token has no "nonce" attribute." because it trying to get value token value in Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider line 66

I dont know why is inside it but if I override authentication_provider_class two AuthenticationProviders work

```php
   public function authenticate(TokenInterface $token)
    {
        if (!$token->hasAttribute('nonce'))
            return;

        return parent::authenticate($token);
    }
```

What is wrong here?

Thanks in advance djoos!
