### ISSUE TITLE
I'm stucked: authorize logged in users or use WSSE to authorize one

### ISSUE THREAD

**Issue by bertoost** [djoos/EscapeWSSEAuthenticationBundle#74]
Hi,

I am a little bit stucked with my project where I want to achieve opening API URLs (FOSRestBundle) as authenticated user (ROLE_ADMIN) and using WSSE header for non-authenticated user. So basically, any API URL should be accessible when:

1. Already authenticated as user (ROLE_ADMIN from FOSUserBundle)
2. The X-WSSE header is provided

Unfortunate I am not allowed to share project specific details; but here some configuration parts

```
security:
  firewalls:
    api_secured:
      pattern: ^/api
      wsse:
        realm: "Secured with WSSE"
        profile: "UsernameToken"
        encoder:
          algorithm: sha1
    secured_area:
      pattern: ^/
      anonymous: ~
      form_login:
      ...
```
The /api URLs are also inside "access_control"

```
  access_control:
    ...
    - { path: ^/api, roles: [ROLE_ADMIN, ROLE_API] }
    ...
```

The ROLE_API is assigned to a "memory user", which is used for external access.
It's no problem to move this user to FOSUserBundle if that would fix this :-)

Besides that, I have setupped a "chain_provider" like this;

```
  providers:
    chain_provider:
      chain:
        providers: [main, wsse_users]
    ...
```

WSSE configuration (default);

```
# Escape WSSE authentication configuration
escape_wsse_authentication:
  authentication_provider_class: Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider
  authentication_listener_class: Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener
  authentication_entry_point_class: Escape\WSSEAuthenticationBundle\Security\Http\EntryPoint\EntryPoint
  authentication_encoder_class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
```

I also use "PdoSessionHandler" to store sessions in the database.

Many many thanks for any help getting this to work.

**Comment by djoos** [comment]
Hi Bert,

sorry for the delay in getting back to you. Have you been able to crack the issue you were experiencing?

I'll close this issue for now, but please do let me know if you have any further issues, so we can reopen this thread and get to the bottom of it...

Thanks!
David

**Comment by bertoost** [comment]
No not yet fixed it.
I am unable to reach /api URLs when I am logged in normally. This is necessary to test responses before getting it in production.
Please some help would be great.

**Comment by djoos** [comment]
Hi Bert,

"_I am unable to reach /api URLs when I am logged in normally_"
Would you be able to let me know what error message you get? Is it the WSSE Auth kicking in and giving you a 403, or...?

You mention you've set up a chain provider - have you tried adding this one explicitly to the api_secured-firewall as provider? Or have you tried using your non-WSSE provider for the api_secured firewall in dev just to get it going as a logged in user?

```
security:
  firewalls:
    api_secured:
    ...
        provider: chain_provider
```

Thanks in advance for your feedback!
David
